### PR TITLE
Reviewers don't like the static version string...

### PR DESCRIPTION
**Pull request by muffgaga**
- upon Björn's request :)

### CODE REVIEW

**Comment by muffgaga** [comment]
Maybe Björn has some ideas... I tried to use the "git hash + dirty flag", but this looks rather "technical" for the PDF version.

**Comment by apdavison** [comment]
This is not how I interpreted the reviewers' comment. How about a version string based on the date, e.g. "Version 2016.09.09.1"? This has the advantage (compared to the Git hash) that it is easy to tell which version is newer (supposing you have two PDFs, for example).

**Comment by muffgaga** [comment]
Ok, I'll postfix the build date to the filename.

**Comment by muffgaga** [comment]
In `latexpdf` mode, the output filename is something like:
`HBPNeuromorphicComputingPlatformGuidebook-20160929081215_0136e75.pdf`
and the PDF cover page contains `Release 2016-09-29 08:12:15 (0136e75)`.

**Pull request merged**
